# P2P Semantic Router Production/Containerized Configuration

network:
  default_host: "bootstrap-node"
  default_port: 5000
  timeout_sec: 3.0
  number_of_nodes: 5

dht:
  hash_bits_m: 160
  replication_factor: 2
  stabilize_interval_sec: 1.0

storage:
  centroids:
    synthetic_path: "data/models/synthetic_centroids.json"
    kaggle_dataset_path: "data/models/kaggle_centroids.json"
  data:
    synthetic_path: "data/raw/synthetic_data.json"
    kaggle:
      raw_path: "data/raw/udemy_courses.csv"
      normalized_path: "data/raw/normalized_kaggle_courses.json"
  num_courses: 500

