#!/usr/bin/env python3
"""Emit a docker-compose file for an arbitrary-size virtual-node ring.

`docker-compose.async_vnodes.yml` hardcodes five services, which caps the ring
at 5 x NUM_VNODES. The N/K ratio sweep needs N to vary over more than an order
of magnitude, so the compose file becomes a GENERATED artifact rather than a
checked-in constant.

Ring size is CONTAINERS x VNODES, and the two are not interchangeable:

  containers  OS processes. Real parallelism -- one interpreter, one GIL each.
  vnodes      asyncio ring identities sharing a single event loop inside one
              process. Cheap in memory, but they serialise against each other.

Hop counts are message counts and are unaffected by how the ring is split
between the two; CONVERGENCE TIME is not. Prefer more containers up to the
core count of the host, then grow vnodes.

`evaluate.py` derives node addresses as containers x vnodes_per_container, so
every container must host the SAME number of vnodes -- hence both are given
explicitly rather than deriving them from a target N.

STATIC IPs matter for correctness here, not just tidiness. Node identity is
SHA-1 of the RESOLVED IP (get_addr_hash -> _resolve_ip), which is Chord's own
convention, so ring topology follows whatever addresses Docker hands out. Compose
creates containers concurrently, making that assignment a RACE: the same compose
file yields a DIFFERENT ring between runs and between machines. Recall and hops
are insensitive to this, but every disaster quantity (which node is heaviest, how
many clusters die with it, how many queries go blank) is not. Across a c-ladder
that would confound the ring draw with the topology change being measured, so
addresses are pinned and the draw becomes a controlled variable -- vary it
deliberately with --subnet when you WANT a different draw.

    python3 containerized_environment/gen_compose_vnodes.py \
        --containers 22 --vnodes 25 --out /tmp/compose.550.yml
"""
import argparse
import ipaddress
import os

HEADER = """# GENERATED by gen_compose_vnodes.py -- do not edit by hand.
# Ring: {containers} containers x {vnodes} vnodes = {total} ring identities.
#
#   ARCH=async_semantic docker compose -f {out} up -d --build
#   docker compose -f {out} run --rm runner -m src.benchmarks.containerized.evaluate ...
#   docker compose -f {out} down --remove-orphans

x-vnode-common: &vnode-common
  image: p2p-semantic-router:latest
  build:
    context: ..
    dockerfile: containerized_environment/Dockerfile
  entrypoint: ["python", "containerized_environment/async_app_vnodes.py"]
  environment:
    - CONFIG_PATH=/app/containerized_environment/config.vnodes.yaml{blas_env}
  volumes:
    - ../data:/app/data
    - ../src:/app/src
    - ./async_app_vnodes.py:/app/containerized_environment/async_app_vnodes.py
    - ${{CONFIG_FILE:-{config}}}:/app/containerized_environment/config.vnodes.yaml

services:
"""

BLAS_ENV = """
    - OMP_NUM_THREADS={n}
    - OPENBLAS_NUM_THREADS={n}
    - MKL_NUM_THREADS={n}
    - NUMEXPR_NUM_THREADS={n}"""

NETWORK = """
networks:
  ringnet:
    driver: bridge
    ipam:
      config:
        - subnet: {subnet}
"""

BOOTSTRAP = """  av-bootstrap:
    <<: *vnode-common
    container_name: av-bootstrap
    networks:
      ringnet:
        ipv4_address: {ip}
    command: ["--arch", "${{ARCH:-async_semantic}}", "--ip", "av-bootstrap", "--port", "5000",
              "--num_vnodes", "{vnodes}", "--vnode_stagger_sec", "{stagger}"]

"""

WORKER = """  av-node-{i}:
    <<: *vnode-common
    container_name: av-node-{i}
    depends_on: [av-bootstrap]
    networks:
      ringnet:
        ipv4_address: {ip}
    command: ["--arch", "${{ARCH:-async_semantic}}", "--ip", "av-node-{i}", "--port", "5000",
              "--num_vnodes", "{vnodes}", "--vnode_stagger_sec", "{stagger}",
              "--bootstrap", "av-bootstrap:5000"]

"""

RUNNER = """  runner:
    <<: *vnode-common
    container_name: av-runner
    profiles: [runner]
    entrypoint: ["python"]
    depends_on: [{deps}]
    networks:
      ringnet:
        ipv4_address: {ip}
"""


def container_names(containers):
    return ["av-bootstrap"] + [f"av-node-{i}" for i in range(1, containers)]


def host_ip(subnet, index):
    """index-th usable address in `subnet`, offset by 2 so .0 (network) and .1
    (Docker's gateway) stay clear. Deterministic: container i always lands on the
    same address, which is what makes the ring reproducible."""
    net = ipaddress.ip_network(subnet, strict=False)
    addr = net.network_address + 2 + index
    if addr not in net:
        raise SystemExit(f"--subnet {subnet} too small for {index + 1} containers")
    return str(addr)


def render(containers, vnodes, out, config, stagger, subnet, blas_threads):
    if containers < 2:
        raise SystemExit("--containers must be at least 2 (bootstrap + one worker)")
    blas_env = BLAS_ENV.format(n=blas_threads) if blas_threads and blas_threads > 0 else ""
    parts = [HEADER.format(containers=containers, vnodes=vnodes,
                           total=containers * vnodes, out=out, config=config,
                           blas_env=blas_env)]
    parts.append(BOOTSTRAP.format(vnodes=vnodes, stagger=stagger,
                                  ip=host_ip(subnet, 0)))
    for i in range(1, containers):
        parts.append(WORKER.format(i=i, vnodes=vnodes, stagger=stagger,
                                   ip=host_ip(subnet, i)))
    # The runner is not a ring member; park it well clear of the node block so
    # adding containers never collides with it.
    parts.append(RUNNER.format(deps=", ".join(container_names(containers)),
                               ip=host_ip(subnet, 1000)))
    parts.append(NETWORK.format(subnet=subnet))
    return "".join(parts)


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--containers", type=int, required=True,
                   help="Physical containers (OS processes). Keep <= host core count.")
    p.add_argument("--vnodes", type=int, required=True,
                   help="Ring identities per container. Same for every container: "
                        "evaluate.py enumerates addresses as containers x this.")
    p.add_argument("--out", required=True, help="Path to write the compose file")
    p.add_argument("--config", default="./config.vnodes.yaml",
                   help="Host-side node config mounted into every container "
                        "(selects the centroid artifact, i.e. K)")
    p.add_argument("--stagger", type=float, default=2.0,
                   help="Seconds between successive vnode joins WITHIN a container. "
                        "Lower it for large --vnodes or boot dominates the run; the "
                        "benchmark's convergence gates are the real correctness check.")
    p.add_argument("--subnet", default="172.28.0.0/16",
                   help="Subnet for the pinned ring addresses. Node identity is a hash "
                        "of the IP, so CHANGING THIS CHANGES THE RING DRAW -- use a "
                        "different subnet to sample a different topology deliberately.")
    p.add_argument("--blas-threads", type=int, default=0,
                   help="Cap BLAS/OpenMP threads per container (0 = uncapped). NumPy "
                        "otherwise spawns one thread per host core INSIDE EVERY "
                        "container, so a 50-container ring on a 48-core box thrashes. "
                        "Rule of thumb: max(1, cores // containers).")
    args = p.parse_args()

    text = render(args.containers, args.vnodes, args.out, args.config, args.stagger,
                  args.subnet, args.blas_threads)
    os.makedirs(os.path.dirname(os.path.abspath(args.out)) or ".", exist_ok=True)
    with open(args.out, "w") as f:
        f.write(text)
    names = container_names(args.containers)
    print(f"wrote {args.out}")
    print(f"ring  : {args.containers} containers x {args.vnodes} vnodes "
          f"= {args.containers * args.vnodes} identities")
    print(f"boot  : ~{args.stagger * args.vnodes:.0f}s of staggered vnode joins per container")
    print(f"ips   : {host_ip(args.subnet, 0)} .. {host_ip(args.subnet, args.containers - 1)} "
          f"(pinned; subnet {args.subnet})")
    print(f"blas  : {args.blas_threads} thread(s)/container"
          if args.blas_threads > 0 else "blas  : uncapped")
    # The benchmark needs this list; print it so the driver can capture it.
    print("CONTAINERS=" + ",".join(names))


if __name__ == "__main__":
    main()
